spring.application.name=re-amigos-practice
#spring.datasource.url=jdbc:postgresql://localhost:5232/naza
spring.datasource.url=jdbc:postgresql://localhost:5432/sammy
spring.datasource.username=sammy
spring.datasource.password=chukwunaza123uel
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.output.ansi.enabled=always
